# Generated by Django 3.0.14 on 2022-08-09 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferdmedia', '0003_auto_20220809_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='users/%Y/%m/%d'),
        ),
    ]
